### ISSUE TITLE
Error: Unsupported MIME type: image/webp

### ISSUE THREAD

**Issue by MrlolDev** [jimp-dev/jimp#1246]
# Expected Behavior

Read the image to crop it

# Current Behavior

Error: Unsupported MIME type: image/webp
    at Jimp.throwError (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\utils\dist\index.js:21:13)
    at Jimp.parseBitmap (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\core\dist\utils\image-bitmap.js:159:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  methodName: 'constructor'
}
# Failure Information (for bugs)

Error: Unsupported MIME type: image/webp
    at Jimp.throwError (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\utils\dist\index.js:21:13)
    at Jimp.parseBitmap (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\core\dist\utils\image-bitmap.js:159:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  methodName: 'constructor'
}
## Steps to Reproduce

```
 console.log(`reading image ${img.id}`);
      let imgFile = await getImageFromUrl(imgUrl);
      const image = await Jimp.read(imgFile);
      console.log(`cropping image ${img.id}`);
```
Image: https://angbrsnflkxfamwrvabk.supabase.co/storage/v1/object/public/mj/1115131652910362654-10.png

## Context

- Jimp Version: 0.22.8
- Operating System: windows 11
- Node version: 18.16

## Failure Logs
```Error: Unsupported MIME type: image/webp
    at Jimp.throwError (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\utils\dist\index.js:21:13)
    at Jimp.parseBitmap (D:\projects\loick.team\projects\turing\dev\Data-cleaning\node_modules\@jimp\core\dist\utils\image-bitmap.js:159:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  methodName: 'constructor'
}```

**Comment by fahinr** [comment]
Bit late but it seems like the image you're trying to load is webp. From the document, the only supported file types are bmp, gif, jpeg, png, and tiff.

**Comment by stephanebachelier** [comment]
@MrlolDev  Webp is not supported by the library as indicated in the README.

**Comment by hipstersmoothie** [comment]
closing in favor of #144
