### ISSUE TITLE
Uncaught exception with malformed PNG

### ISSUE THREAD

**Issue by Lambdac0re** [jimp-dev/jimp#1261]
# Expected Behavior

Either not crashing or properly handling of the error (useful error message for example).

# Current Behavior

```
Error: End-Of-Stream
    at BufferTokenizer.peekBuffer (C:\js\yeet-ocr\node_modules\strtok3\lib\BufferTokenizer.js:44:19)
    at BufferTokenizer.readBuffer (C:\js\yeet-ocr\node_modules\strtok3\lib\BufferTokenizer.js:30:38)
    at BufferTokenizer.readToken (C:\js\yeet-ocr\node_modules\strtok3\lib\AbstractTokenizer.js:25:32)
    at readChunkHeader (C:\js\yeet-ocr\node_modules\file-type\core.js:978:29)
    at _fromTokenizer (C:\js\yeet-ocr\node_modules\file-type\core.js:984:24)
    at async getMIMEFromBuffer (C:\js\yeet-ocr\node_modules\@jimp\core\dist\utils\image-bitmap.js:19:30)
    at async Jimp.parseBitmap (C:\js\yeet-ocr\node_modules\@jimp\core\dist\utils\image-bitmap.js:149:16)
```

# Failure Information (for bugs)

## Steps to Reproduce

Use attached file:
```
Jimp
.read(buffer)
.then(jimpObj => jimpObj.getBufferAsync(Jimp.MIME_PNG))
```

## Context

- Jimp Version: 0.22.10
- Operating System: Windows 10
- Node version: 16

## Failure Logs
![broken-png](https://github.com/jimp-dev/jimp/assets/11350544/00eb4ab8-d155-4a10-be5c-5d306789d275)

**Comment by Lambdac0re** [comment]
The same file gives you this useful error message with `sharp`:
`"Input buffer has corrupt header: pngload_buffer: end of stream"`

**Comment by Lambdac0re** [comment]
Here is another example:

https://i.imgur.com/dYKD1.png
