### ISSUE TITLE
Cannot find module `@jimp/plugin-print/load-font`, when used in Jest test

### ISSUE THREAD

**Issue by domdomegg** [jimp-dev/jimp#1325]
# Expected Behavior

Can run a basic test with Jest using Jimp 1.2.0

# Current Behavior

```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Cannot find module '@jimp/plugin-print/load-font' from 'node_modules/jimp/dist/commonjs/index.js'

    Require stack:
      node_modules/jimp/dist/commonjs/index.js
      src/lib/2-png-to-jpg.ts
      src/lib/index.ts
      src/App.tsx
      src/App.test.tsx

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (node_modules/jimp/src/index.ts:171:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.355 s, estimated 1 s
Ran all test suites related to changed files.
```

# Failure Information (for bugs)

The rest of Jimp seems to load perfectly fine in the environment. I don't think I use this plugin, and commenting out line 166 of `jimp/dist/commonjs/index.js` (i.e. `var load_font_1 = require("@jimp/plugin-print/load-font");`) makes the tests pass.

I think this is a Jimp issue rather than a Jest issue/misconfiguration given that the rest of Jimp works fine in this environment, and it's just this one line it has issue with.

## Steps to Reproduce

1. Set up a create react app project
2. Import Jimp in the main App component
3. Run a very simple test:
    ```ts
    import { render, screen } from '@testing-library/react';
    import App from './App';
    
    test('renders title', () => {
      render(<App />);
      const titleElement = screen.getByText("Learn React");
      expect(titleElement).toBeInTheDocument();
    });
    ```

## Context

- Jimp Version: 1.2.0
- Operating System: macOS Sonoma 14.6.1
- Node version: v22.5.1

**Comment by domdomegg** [comment]
Minimal repro here: https://github.com/domdomegg/jimp-1325-repro

**Comment by hipstersmoothie** [comment]
That's using react.scripts with is on an old version of jest (27)

Reading through [this issue](https://github.com/jestjs/jest/issues/9771) it seems like support for the feature came in jest >28

Could you try updating? If you can't you might be able to write your own custom resolver for jest

**Comment by domdomegg** [comment]
Installing Jest 28 (or 29) doesn't seem to change the error, unfortunately.

**Comment by hipstersmoothie** [comment]
I got the tests to pass there by using `jest-node-exports-resolver` so it indeed does seem to be an issue in jest resolving package exports

![CleanShot 2024-09-03 at 10 43 22](https://github.com/user-attachments/assets/cc7ea0ee-7c66-41ab-8c5a-94d9860ec6f3)

This does seem to be fixed in newer versions of jest. I just checked here

https://github.com/hipstersmoothie/jimp-jest

**Comment by Shelagh-Lewins** [comment]
Hiya, I think Jimp is awesome but I'm seeing the same error, however when I run the app, not in a test context. I'm using jimp in a Meteor JS app and the problem happened when I upgraded from Jimp 0.9 to 1.6.0. I use require() in various places so I don't know what's different about this usage that means it isn't resolved?
