### ISSUE TITLE
LoadFont dont work!

### ISSUE THREAD

**Issue by AndreZila01** [jimp-dev/jimp#1347]
Previously, i was use your code when Jimp has on version ^0.22.10. But when i update the library i received that warning:
"Cannot read properties of undefined (reading 'slice')".
I would like know what happend to the library. And where i can found documentation of JIMP to JavaScript!

``` 
const Jimp = require('jimp');

async function load() {

    let content = "Test"

    await Jimp.loadFont(Jimp.FONT_SANS_128_WHITE).then(async (font) => {
        let count = 0;
        await Jimp.read(`./FicheirosS/1.JPG`).then(async (fir_img) => {

            fir_img.print(
                font,
                250,
                2000,
                content,
            );

            fir_img.write(`./FicheirosC/${count++}.JPG`);
        });
    });


}

load();
```

Thanks for the support!

**Comment by AndreZila01** [comment]
Message of error i was received:

> Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'slice')
    at isBinary (c:\Users\Andre\Desktop\Rita\AddFonte\node_modules\@jimp\plugin-print\dist\commonjs\load-bitmap-font.js:24:31)
    at parseFont (c:\Users\Andre\Desktop\Rita\AddFonte\node_modules\@jimp\plugin-print\dist\commonjs\load-bitmap-font.js:31:9)
    at loadBitmapFontData (c:\Users\Andre\Desktop\Rita\AddFonte\node_modules\@jimp\plugin-print\dist\commonjs\load-bitmap-font.js:103:16)
    at loadFont (c:\Users\Andre\Desktop\Rita\AddFonte\node_modules\@jimp\plugin-print\dist\commonjs\load-font.js:28:69)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues:95:5)

**Comment by FerdinandRamos** [comment]
Did you figure out a solution to this? I'm having the same issue

**Comment by AndreZila01** [comment]
Nooo... i'm using the old version number "^0.22.10"

**Comment by isntfunny** [comment]
Same issue here.. Any solutions?

**Comment by BosseKarat** [comment]
Same issue here using TypeScript when using the example provided by the docs - http://jimp-dev.github.io/jimp/api/jimp/functions/loadfont/

`Cannot find module 'jimp/fonts' or its corresponding type declarations.`

This is a result of missing node modules, incorrect paths, or missing type declaration files.

**Comment by whchi** [comment]
you can try 
```js
import { loadFont } from 'jimp';
```

**Comment by SeaN0X** [comment]
i had the exact same issue, but i updated to the most recent version and used those as my code:


```
import { FONT_SANS_128_WHITE } from "jimp/fonts";
...
 const font = await loadFont(FONT_SANS_128_WHITE);
```
it worked for me

**Comment by BosseKarat** [comment]
Yes, you can get around it by adjusting your tsconfig to e.g 

```
        "target": "ES2022",
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
```

That is not an option for some people though.

**Comment by Ronexan** [comment]
> i had the exact same issue, but i updated to the most recent version and used those as my code:
> 
> ```
> import { FONT_SANS_128_WHITE } from "jimp/fonts";
> ...
>  const font = await loadFont(FONT_SANS_128_WHITE);
> ```
> 
> it worked for me

Thanks! This worked!
