### ISSUE TITLE
Doesn't bundle with Browserify

### ISSUE THREAD

**Issue by montyanderson** [jimp-dev/jimp#642]
# Expected Behavior

Jimp should bundle with browserify without any errors.

```
$ browserify -r "jimp"
```

# Current Behavior

```
$ browserify -r "jimp"
Error: Cannot find module './src/converter' from '[...]/node_modules/jimp/browser/lib'
    at [...]/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load ([...]/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex ([...]/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at [...]/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:158:21)

```

# Failure Information (for bugs)

## Steps to Reproduce

```
$ npm install -g browserify
$ npm install jimp
$ browserify -r "jimp"
```

**Screenshots**

## Context

- Jimp Version: 0.5.3
- Operating System: Ubuntu 18
- Node version: 10.7.0

**Comment by hipstersmoothie** [comment]
Good thing we already did it you should be able to access the browser version via 

```js
const Jimp = require('jimp/browser/lib/jimp');
```

let me know if that works!

**Comment by griffin2000** [comment]
Same results for me with that file (same results just pasting that line into a js file and browserifying that) , in version 0.5.6:

```
λ browserify -r "jimp/browser/lib/jimp"
Error: Cannot find module './src/converter' from 'C:\Axum\github\jimp-example\node_modules\jimp\browser\lib'
    at C:\Users\garet\AppData\Roaming\nvm\v8.9.1\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\garet\AppData\Roaming\nvm\v8.9.1\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\garet\AppData\Roaming\nvm\v8.9.1\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\garet\AppData\Roaming\nvm\v8.9.1\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by hipstersmoothie** [comment]
Hmmm i honestly have no clue. Ive been thinking of switching over to webpack soon to make a browser version but idk if that would solve this problem. I honestly have no clue how to go about debugging that as 'jimp has no `'./src/converter'`

**Comment by WasabiThumb** [comment]
Sorry to bump, any updates?

**Comment by hipstersmoothie** [comment]
Pretty sure I've fixed this now. If you have any further issue feel free to open a new one.
