### ISSUE TITLE
Error: The source must be a Jimp image

### ISSUE THREAD

**Issue by RahulBatra065** [jimp-dev/jimp#804]
# Expected Behavior
output an image with the given composite behavior

# Current Behavior

throws error

# Failure Information (for bugs)

## Steps to Reproduce

CODE: 
var Jimp = require('jimp');

function createImage() {
    var bg = new Jimp(1280, 720);
    var avatar = Jimp.read('qd.png');
    bg.composite(avatar, 0, 0);
    bg.writeAsync('gg.png')

}
createImage();
**Screenshots**

## Context

- Jimp Version: 0.8.4
- Operating System: Mac OS X 10.14.6 (Mojave)
- Node version: v10.15.3

## Failure Logs
/Users/rahulbatra/Documents/nodejs-test/node_modules/@jimp/utils/dist/index.js:40
  throw error;
  ^

Error: The source must be a Jimp image
    at Jimp.throwError (/Users/rahulbatra/Documents/nodejs-test/node_modules/@jimp/utils/dist/index.js:33:13)
    at Jimp.composite (/Users/rahulbatra/Documents/nodejs-test/node_modules/@jimp/core/dist/composite/index.js:37:30)
    at createImage (/Users/rahulbatra/Documents/nodejs-test/index.js:49:8)
    at Object.<anonymous> (/Users/rahulbatra/Documents/nodejs-test/index.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)

**Comment by Neztore** [comment]
Forgive me if I'm being obtuse here, but don't you have to await the Jimp.read call since it returns a promise?
