### ISSUE TITLE
Yarn test fails for fresh clone 

### ISSUE THREAD

**Issue by mubaidr** [jimp-dev/jimp#850]
# Expected Behavior

`Yarn test` should complete successfully with fresh clone. 

# Current Behavior

Wanted to add a feature to jimp library. `Yarn test` failed with code 1. 

# Failure Information (for bugs)

Tried running `yarn test` on both windows cmd and debian bash. Fails on both. 

## Steps to Reproduce

1. clone
2. `yarn`
3. `yarn test`

**Screenshots**
NA

## Context

- Jimp Version:
- Operating System: Windows 10, Debian 10
- Node version: 13

## Failure Logs
```bash
user@USER-DESKTOP:/mnt/d/current/jimp$ yarn test
yarn run v1.22.0
$ cross-env BABEL_ENV=test mocha --require @babel/register './packages/**/test/**/*.test.js' --require ts-node/register ./packages/**/test/*.test.ts
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Error: Cannot find module '/mnt/d/current/jimp/node_modules/jimp/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:315:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:703:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/d/current/jimp/packages/cli/src/cli.ts:45:30)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/mnt/d/current/jimp/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at newLoader (/mnt/d/current/jimp/node_modules/pirates/lib/index.js:104:7)
    at Object.require.extensions.<computed> [as .ts] (/mnt/d/current/jimp/node_modules/ts-node/src/index.ts:442:12)         at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/d/current/jimp/packages/cli/test/cli.test.ts:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module.m._compile (/mnt/d/current/jimp/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at newLoader (/mnt/d/current/jimp/node_modules/pirates/lib/index.js:104:7)
    at Object.require.extensions.<computed> [as .ts] (/mnt/d/current/jimp/node_modules/ts-node/src/index.ts:442:12)         at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /mnt/d/current/jimp/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/d/current/jimp/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/mnt/d/current/jimp/node_modules/mocha/lib/mocha.js:811:10)
    at Object.exports.singleRun (/mnt/d/current/jimp/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/mnt/d/current/jimp/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/mnt/d/current/jimp/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/mnt/d/current/jimp/node_modules/mocha/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/mnt/d/current/jimp/node_modules/mocha/node_modules/yargs/yargs.js:1087:28)        at Object.parse (/mnt/d/current/jimp/node_modules/mocha/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/mnt/d/current/jimp/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/mnt/d/current/jimp/node_modules/mocha/bin/mocha:154:29)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by GlitchyPSIX** [comment]
Did you do `yarn build`?

**Comment by hipstersmoothie** [comment]
They are passing
