### ISSUE TITLE
Converted font file not loading

### ISSUE THREAD

**Issue by zigman32** [jimp-dev/jimp#851]
# Expected Behavior

My font file should load properly. I have a .ttf font file, which I have converted into a .fnt file using FontForge. 

# Current Behavior

When I try to load the font file using Jimp.loadFont() I get this error:

Error: no named row at line 5
    at splitLine (C:\Users\zigma\Downloads\Megasync\Jerrybot\node_modules\parse-bmfont-ascii\index.js:49:11)
    at parseBMFontAscii (C:\Users\zigma\Downloads\Megasync\Jerrybot\node_modules\parse-bmfont-ascii\index.js:18:20)
    at parseFont (C:\Users\zigma\Downloads\Megasync\Jerrybot\node_modules\load-bmfont\index.js:26:19)
    at handleData (C:\Users\zigma\Downloads\Megasync\Jerrybot\node_modules\load-bmfont\index.js:45:5)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

I am using version 6.13.4 of jimp

Included are the font files before and after conversion:

[FragileBombers.zip](https://github.com/oliver-moran/jimp/files/4285264/FragileBombers.zip)

**Comment by julianStreibel** [comment]
Same here

**Comment by zigman32** [comment]
I think I wound up solving this issue. Turns out fontforge was the problem. I wound up using a different converter and it worked fine.

**Comment by rzorzal-wa** [comment]
@zigman32 what other converter did you use ? I facing the same problem :(

**Comment by rzorzal-wa** [comment]
nevermind, I have use https://github.com/libgdx/libgdx/wiki/Hiero and it is working fine. But I think Jimp needs a ttf font handler like openCV does.

**Comment by bierzorutas** [comment]
Same problem here, would be nice that jimp can handle ttf fonts, I am close to have to stop use JIMP after several hours of problems with fonts, conversions, accents...
