### ISSUE TITLE
Crash if you read url with a redirect

### ISSUE THREAD

**Issue by IVA-apps** [jimp-dev/jimp#909]
Example: 

```
Jimp.read('https://lk.exdom.ru/pikchers/7b/15/5f0b65287c693538212a157b.jpg', (err, pic) => {
    // any code
    console.log('no run');
});
```

CONSOLE =>

```
/Users/victor/dev/ws/ja/node_modules/phin/lib/phin.compiled.js:1
'use strict';var _typeof=typeof Symbol==='function'&&typeof Symbol.iterator==='symbol'?function(obj){return typeof obj}:function(obj){return obj&&typeof Symbol==='function'&&obj.constructor===Symbol&&obj!==Symbol.prototype?'symbol':typeof obj};var http=require('http');var https=require('https');var url=require('url');var qs=require('querystring');var zlib=require('zlib');var util=require('util');var phin=function phin(opts,cb){if(typeof opts!=='string'){if(!opts.hasOwnProperty('url')){throw new Error('Missing url option from options for request method.')}}var addr=(typeof opts==='undefined'?'undefined':_typeof(opts))==='object'?url.parse(opts.url):url.parse(opts);var options={'hostname':addr.hostname,'port':addr.port||(addr.protocol.toLowerCase()==='http:'?80:443),'path':addr.path,'method':'GET','headers':{},'auth':addr.auth||null,'parse':'none','stream':false};if((typeof opts==='undefined'?'undefined':_typeof(opts))==='object'){options=Object

TypeError: Cannot read property 'toLowerCase' of null
    at phin (/Users/victor/dev/ws/ja/node_modules/phin/lib/phin.compiled.js:1:744)
    at module.exports (/Users/victor/dev/ws/ja/node_modules/@jimp/core/dist/request.js:44:5)
    at loadFromURL (/Users/victor/dev/ws/ja/node_modules/@jimp/core/dist/index.js:104:27)
    at /Users/victor/dev/ws/ja/node_modules/@jimp/core/dist/index.js:111:14
    at /Users/victor/dev/ws/ja/node_modules/@jimp/core/dist/request.js:48:9
    at IncomingMessage.<anonymous> (/Users/victor/dev/ws/ja/node_modules/phin/lib/phin.compiled.js:1:2100)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by avichal-neweradeveloper** [comment]
Do you got the solution

**Comment by avichal-neweradeveloper** [comment]
hey I got the solution for me it was the req.isAuthenticated() method of passport which was causing the error I removed it from my get route for image reading with gridfs and multer

**Comment by Explosion-Scratch** [comment]
I am getting this error with Jimp as well, not sure what I am doing wrong, half the time my server works flawlessly, and the other half of the time it crashes because it cannot read property 'lowercase' of null. 😭 Here's my entire code if someone wants to help me:
<details>
<summary>Code</summary>

```js
const express = require('express');
var Jimp = require('jimp');
const app = express();

app.get('/', (req, res) => {
	if (!req.query.q){
		res.json({error: "No image provided, provide one through a 'q' parameter."});
		return;
	}
  Jimp.read("https://cors.explosionscratc.repl.co/" + req.query.q.replace(/^(?:http|https)\:\/\//, ""))
  .then(async (image) => {
		if (req.query.width || req.query.height){
			let width = +req.query.width || Jimp.AUTO;
			let height = +req.query.height || Jimp.AUTO;
			image.resize(width, height)
		}
		if (req.query.greyscale){
			image.greyscale();
		}
		if (req.query.flipHorizantal || req.query.flipVertical){
			image.flip(req.query.flipHorizantal ? true :  false, req.query.flipVertical ? true :  false)
		}
		if (req.query.invert){
			image.invert();
		}
		if (req.query.brightness){
			if (+req.query.brightness > 1 || +req.query.brightness < -1){
				res.json({error: "Brightness must be between -1 and 1"});
				throw new Error("")
			}
			image.brightness(+req.query.brightness)
		}
		if (req.query.contrast){
			if (+req.query.contrast > 1 || +req.query.contrast < -1){
				res.json({error: "Contrast must be between -1 and 1"});
				throw new Error("")
			}
			image.contrast(+req.query.contrast)
		}
		if (req.query.opacity){
			if (+req.query.opacity > 1 || +req.query.opacity < -1){
				res.json({error: "Opacity must be between -1 and 1"});
				throw new Error("")
			}
			image.opacity(+req.query.opacity)
		}
		if (req.query.blur){
			image.blur(+req.query.blur);
		}
		if (req.query.posterize){
			image.posterize(+req.query.posterize)
		}
		if (req.query.rotate){
			image.rotate(+req.query.rotate)
		}
		if (req.query.crop){
			let a = req.query.crop.split(",");
			if (a.length !== 4){
				res.json({error: "Not enough arguments for crop, crop query must be in the form 'x,y,width,height'"})
				return;
			}
			a = a.map((i) => +i);
			image.crop(...a);
		}
		if (req.query.quality){
			image.quality(+req.query.quality);
		}
		if (req.query.hash) {
			res.json(image.hash(+req.query.hash));
			return;
		}
		if (req.query.scale){
			image.scale(+req.query.scale);
		}
		if (req.query.autoCrop){
			image.autoCrop(+req.query.autoCrop)
		}
		if (req.query.scaleToFit){
			image.scaleToFit(...req.query.scaleToFit.split(",").slice(0,2).map(i => +i))
		}
		if (req.query.pixelate){
			image.pixelate(...req.query.pixelate.split(",").map(i => +i))
		}
		if (req.query.opaque){
			image.opaque();
		}
		if (req.query.text){
			let font = await Jimp.loadFont(Jimp[`FONT_${req.query.font ? req.query.font.replace(" ", "_").toUpperCase() : "SANS_32_BLACK"}`])
			var textWidth = Jimp.measureText(font, text);
    var textHeight = Jimp.measureTextHeight(font, text);
			await image.print(font, req.query.fontX || 0, req.query.fontY || 0, {
				text: req.query.text,
				alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER,
				alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE,
			}, textWidth,  textHeight)
			console.log(font, req.query, image)
		}
		let modifiers = [];
		if (req.query.hueRotate || req.query.hue){
			modifiers.push({apply: "spin", params: [+(req.query.hue || req.query.hueRotate)]})
		}
		if (req.query.darken){
			modifiers.push({apply: "darken", params: [+req.query.darken]});
		}
		if (req.query.saturate){
			modifiers.push({apply: "saturate", params: [+req.query.saturate]});
		}
		if (modifiers.length > 0){
			image.color(modifiers)
		}
		return image
	})
	.then(async (resized) => {
		let img = await resized.getBufferAsync(req.query.mime || req.query.mimeType || "image/png");
		res.writeHead(200, {
			'Content-Type': req.query.mime || req.query.mimeType || "image/png",
			'Content-Length': img.length
		});
		res.end(img);
	})
	.catch((e) => {
		console.log(e);
		try {
			res.json({error: e.message})
		} catch(e){
			// Res may be sent already
		}
	})
});

app.listen(3000, () => {
  console.log('server started');
});
```
</details>

**Comment by Explosion-Scratch** [comment]
@oliver-moran

**Comment by usabe** [comment]
Hello @oliver-moran 

Recently I came across the same issue getting the error "Cannot read property 'toLowerCase' of null". Finally my debugging shows that the root cause of this issue comes from this line in the function "loadFromURL" in the file 
 @jimp/core/dist/index.js :

**Comment by daniar23337** [comment]
> Чтобы решить эту проблему, нам может потребоваться добавить протокол и хост перед «местоположением» относительного пути при назначении его для options.url. Таким образом, я временно исправил это на своем серверном узле, и он отлично работает для перенаправлений.
> 
hardly anyone will answer, but someone can formulate the solution in more detail
