### ISSUE TITLE
 Cannot read property 'interlace' of undefined

### ISSUE THREAD

**Issue by cll123456** [jimp-dev/jimp#973]

**Comment by moom0o** [comment]
Oh my god, the only issue I can find with the same problem and it's not answered. FML
```
TypeError: Cannot read property 'interlace' of undefined
    at module.exports (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/parser-sync.js:79:16)
    at Object.exports.read [as image/png] (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/png/node_modules/pngjs/lib/png-sync.js:10:10)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/utils/image-bitmap.js:196:53)
    at Jimp.parseBitmap (/home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:431:32)
    at /home/debian/MOO/moobot/9b9t/node_modules/@jimp/core/dist/index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}
```

**Comment by moom0o** [comment]
It was because I was reading the file while it was being written.
